esphome:
  name: jkbms-ble-gateway

esp32:
  board: esp32dev
  framework:
    type: arduino

# Cấu hình kết nối WiFi
wifi:
  ssid: VanTC
  password: alsvn123

# Bật API kết nối Home Assistant / MQTT
api:
  encryption:
    key: tar9tjtnP8LhENwROVvkKLl+oLYHpAOXSoIzKMjALT4=
ota:
  - platform: esphome

logger:
  level: INFO

# Bật Ble Tracker để ESP32 quét Bluetooth
esp32_ble_tracker:
  # 1. Bổ sung khối ble_client dưới đây
ble_client:
  - id: jkbms_ble_client
    mac_address: "A4:C1:38:0D:C5:D9" # Thay địa chỉ MAC của BMS vào đây

# Tích hợp component JK BMS qua BLE
external_components:
  - source:
      type: local
      path: my_components/esphome-jk-bms/components
      
jk_bms_ble:
  - id: my_jkbms
    ble_client_id: jkbms_ble_client
    protocol_version: JK02_32S
    throttle: 2s

# Danh sách các cảm biến cần lấy dữ liệu
sensor:
  - platform: jk_bms_ble
    jk_bms_ble_id: my_jkbms
    total_voltage:
      name: "JKBMS Total Voltage"
    current:
      name: "JKBMS Current"
    power:
      name: "JKBMS Power"
    state_of_charge:
      name: "JKBMS SOC"
    capacity_remaining:
      name: "JKBMS Capacity Remaining"
    charging_cycles:
      name: "JKBMS Cycles"
    total_charging_cycle_capacity:
      name: "JKBMS Total Cycle Capacity"
    min_cell_voltage:
      name: "JKBMS Min Cell Voltage"
    max_cell_voltage:
      name: "JKBMS Max Cell Voltage"
    min_voltage_cell:
      name: "JKBMS Min Voltage Cell Number"
    max_voltage_cell:
      name: "JKBMS Max Voltage Cell Number"
    delta_cell_voltage:
      name: "JKBMS Delta Cell Voltage"
    average_cell_voltage:
      name: "JKBMS Average Cell Voltage"
    temperature_sensor_1:
      name: "JKBMS Power MOS Temp"
    temperature_sensor_2:
      name: "JKBMS Battery Temp 1"
      
  - platform: jk_bms_ble
    jk_bms_ble_id: my_jkbms
    cell_voltage_1:
      name: "JKBMS Cell Voltage 1"
    cell_voltage_2:
      name: "JKBMS Cell Voltage 2"
    cell_voltage_3:
      name: "JKBMS Cell Voltage 3"
    cell_voltage_4:
      name: "JKBMS Cell Voltage 4"
    cell_voltage_5:
      name: "JKBMS Cell Voltage 5"
    cell_voltage_6:
      name: "JKBMS Cell Voltage 6"
    cell_voltage_7:
      name: "JKBMS Cell Voltage 7"
    cell_voltage_8:
      name: "JKBMS Cell Voltage 8"
    cell_voltage_9:
      name: "JKBMS Cell Voltage 9"
    cell_voltage_10:
      name: "JKBMS Cell Voltage 10"
    cell_voltage_11:
      name: "JKBMS Cell Voltage 11"
    cell_voltage_12:
      name: "JKBMS Cell Voltage 12"
    cell_voltage_13:
      name: "JKBMS Cell Voltage 13"
    cell_voltage_14:
      name: "JKBMS Cell Voltage 14"
    cell_voltage_15:
      name: "JKBMS Cell Voltage 15"
    cell_voltage_16:
      name: "JKBMS Cell Voltage 16"
text_sensor:
  - platform: jk_bms_ble
    jk_bms_ble_id: my_jkbms
    errors:
      name: "JKBMS Error Warning"

switch:
  - platform: jk_bms_ble
    jk_bms_ble_id: my_jkbms
    charging:
      name: "JKBMS Charging Switch"
    discharging:
      name: "JKBMS Discharging Switch"
    balancer:
      name: "JKBMS Balancer Switch"